name: Build and Release

on:
  push:
    branches: [ master ]
    tags:
      - 'v*'
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up JDK 17
      uses: actions/setup-java@v5
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: Initialize
      run: mvn initialize

    - name: Build with Maven
      run: mvn clean compile package

    - name: Upload build artifacts
      uses: actions/upload-artifact@v4
      with:
        name: jcardsim-jars
        path: |
          target/*.jar
          !target/original-*.jar

  release:
    needs: build
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/v')

    steps:
    - uses: actions/checkout@v4

    - name: Set up JDK 17
      uses: actions/setup-java@v5
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: Initialize
      run: mvn initialize

    - name: Build with Maven
      run: mvn clean initialize compile package

    - name: Create Release and Upload Assets
      uses: ncipollo/release-action@v1
      with:
        artifacts: "target/*.jar,!target/original-*.jar"